### ISSUE TITLE
Empty cols

### ISSUE THREAD

**Issue by unitxt** [ComputerWolf/996-Grid#1]
Hi, thanks for your grid sistem its simple and usable.
i have ( 4 content  - 4 empty - 4 content ) if i preview looks : 4 content - 4 content /  empty is on top of 1st col becouse is float, i fix with &nbsp, but i whant know if have in the same sistem something to fix this

thanks!

**Comment by ComputerWolf** [comment]
If you need to have empty columns, the best way is by using the prefix and suffix classes. In your case, the first column class would be "grid_4 suffix_4", which places an empty space of 4 columns after the content columns. The class for the other content would simply be "grid_4".

**Comment by unitxt** [comment]
Thanks! 
i see de css file an find all options
Regards!
